-- Create Schema
DROP SCHEMA IF EXISTS `bestcommerce`;
CREATE SCHEMA `bestcommerce`;
USE `bestcommerce` ;

-- Create Tables
CREATE TABLE IF NOT EXISTS `bestcommerce`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `bestcommerce`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,  
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,    
  `inventory` INT DEFAULT NULL,  
  `category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `bestcommerce`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `payment_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `bestcommerce`.`delivery` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `delivery_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `bestcommerce`.`product_payment` (
    PP_ID BIGINT NOT NULL AUTO_INCREMENT,
    PROD_ID BIGINT,
    PAY_ID BIGINT,
    PRIMARY KEY (PP_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT(ID)
)
ENGINE=InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `bestcommerce`.`product_delivery` (
    PD_ID BIGINT NOT NULL AUTO_INCREMENT,
    PROD_ID BIGINT,
    DEL_ID BIGINT,
    PRIMARY KEY (PD_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (DEL_ID) REFERENCES DELIVERY(ID)
)
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- Add sample data
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Electronics');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Fashion');
INSERT INTO CATEGORY(CATEGORY_NAME) VALUES ('Food');

INSERT INTO PAYMENT(PAYMENT_NAME) VALUES ('Direct');
INSERT INTO PAYMENT(PAYMENT_NAME) VALUES ('In installments');

INSERT INTO DELIVERY(DELIVERY_NAME) VALUES ('Delivery option-1');
INSERT INTO DELIVERY(DELIVERY_NAME) VALUES ('Delivery option-2');
INSERT INTO DELIVERY(DELIVERY_NAME) VALUES ('Delivery option-3');

INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-1', 'Product Description-1', 10, 5.25, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-2', 'Product Description-2', 8, 3.25, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-3', 'Product Description-3', 2, 6.00, 1);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-4', 'Product Description-4', 4, 10.25, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-5', 'Product Description-5', 9, 7.50, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-6', 'Product Description-6', 25, 8, 2);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-7', 'Product Description-7', 17, 15.50, 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-8', 'Product Description-8', 22, 12.25, 3);
INSERT INTO PRODUCT (NAME, DESCRIPTION, INVENTORY, UNIT_PRICE, CATEGORY_ID) VALUES ('Product-9', 'Product Description-9', 17, 16.75, 3);

INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (1, 1);
INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (1, 2);
INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (2, 1);
INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (3, 2);
INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (4, 1);
INSERT INTO PRODUCT_PAYMENT(PROD_ID, PAY_ID) VALUES (4, 2);

INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (1, 1);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (1, 2);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (1, 3);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (2, 3);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (3, 2);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (4, 1);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (4, 3);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (5, 2);
INSERT INTO PRODUCT_DELIVERY(PROD_ID, DEL_ID) VALUES (6, 3);